### ISSUE TITLE
Website Edits: To Do

### ISSUE THREAD

**Issue by sabahzero** [ivamp-consortium/ivamp-consortium.github.io#1]
- [x] change @ to [at] for emails (people page)
- [x] Give a trigger warning for spiders before people access page -- credit @erikfritas 
- [x] Link Github repo on website -- credit @erikfritas 
- [x] Gallery: Organize images, row per row -- credit @erikfritas 
- [x] Check that icon image being moved isn't affected -- credit @erikfritas

**Comment by sabahzero** [comment]
- Add updated member list to Google Drive folder (its own account and gmail?)

**Comment by josephmidura** [comment]
I can help with these issues if you need help with this project. I recommend one issue per bullet point to keep work organized.

**Comment by sabahzero** [comment]
@josephmidura thanks for the generous offer, we'd be happy to receive some help! I'm not well-versed in html and it's namely been me coding the website. Please feel welcome to explore and add recommendations. We're very happy to credit your contributions accordingly.

**Comment by josephmidura** [comment]
I remember the challenges of maintaining a website for my research group when I was in grad school. I'm happy to help how I can.

**Comment by sabahzero** [comment]
Thank you @josephmidura ! Let me know the best route to follow-up with you and will go forward accordingly -- I'm presuming you are well-versed in html? This is where I feel there is likely a lot of code on my end that is repetitive/WET

**Comment by josephmidura** [comment]
I thought I replied to this :facepalm:. We can chat through GitHub or move to a chat app if that makes more sense. Do you have a preference?

**Comment by sabahzero** [comment]
@josephmidura no worries! I'm also quite delayed (2 months later!) Would a Zoom chat be possible? If so, I can schedule one via email for 30-40 minutes. Thank you again for all your help!

**Comment by josephmidura** [comment]
Yes, zoom can work, especially in the evening (I'm assuming you're in the US). Is the email on your profile a good way to reach you?

**Comment by sabahzero** [comment]
Hi @josephmidura, yes! And apologies again for all the delayed replies. Things are started to level out a bit more on my end, fortunately. Thank you for your patience and generous input/time!!

I'm on PST and can create a Zoom and calendar invite once I see the email. I'll keep a lookout!
Hope you've been doing well.

**Comment by sabahzero** [comment]
@josephmidura's suggestions
- Step 1: Fix all the small bugs and updates (ie images, contact page, etc)
- Step 2: Make it look nicer (perhaps a javascript package) @josephmidura may become involved here
- Step 3: Could get a custom URL (but still host website with Github)

**Comment by sabahzero** [comment]
@josephmidura I think you may have accept the 'Writer' invite for me to tag you on these, but let me know if I need to upgrade it. I will probably complete most of the above (updated checkboxes specific to me above, and created new Issue for ones that you would be particularly helpful with based on our meet) by mid- next week (will ping to confirm when done)

https://github.com/ivamp-consortium/ivamp-consortium.github.io/issues/2

**Comment by erikfritas** [comment]
Added warning (at the speed of light by me): "to prepare people, as there may be images that may initially cause fear in some people..."

**Comment by josephmidura** [comment]
@sabahzero I'm getting the notification.

**Comment by sabahzero** [comment]
@erikfritas this is great, thank you!! is there a way to have the warning be a little more minimalist in style (black and white theme, or something a bit less colorful?)

**Comment by erikfritas** [comment]
Yes!!! I will do that now

**Comment by josephmidura** [comment]
The warning page seems a bit unnecessary as people who go to the site should be already familiar with the subject matter.

**Comment by erikfritas** [comment]
@josephmidura but what if someone still doesn't know what's going on on the site?? the name is not self-explanatory, so if the user has a phobia of any of the beings present in the images, it is likely to frighten them, and I assume that is not the purpose of this institution.

**Comment by erikfritas** [comment]
I understand that this could mean one less user in our institution... but at least that way we have less chance of scaring someone.

**Comment by erikfritas** [comment]
@sabahzero did you like the new trigger style?

**Comment by sabahzero** [comment]
It's better!
- Can we make the font bigger (maybe 2x or so)?
- Can we make the 'warning' icon larger? As well as the 'ok' (let's change 'ok' to 'enter site'
- Can we get rid of the contrast with the square, such that it's only the animation part and not the black backdrop (one or the other maybe, instead of having both now)?
- Let's update the phrase to "The Initiative for Venom Associated Microbes and Parasites (iVAMP) website contains images such as spiders and scorpions" @josephmidura we do intend for the site to be for the broader public, but currently focused on the consortium itself
![Screen Shot 2021-09-27 at 10 26 42 PM](https://user-images.githubusercontent.com/16907482/135028330-bfbb743a-bb66-4809-a827-dd57471d4283.png)

**Comment by erikfritas** [comment]
@sabahzero ok i will do it now

**Comment by erikfritas** [comment]
ok, I already finished doing that...

**Comment by erikfritas** [comment]
@sabahzero what do you think??

**Comment by erikfritas** [comment]
about the new style...

**Comment by sabahzero** [comment]
Hi @erikfritas, thanks for taking the time! I have a few thoughts, but I also have a few deadlines this week. Let me get back to you either Friday or mid- next week. Feel very welcome to address other items in the meantime, I'm going to go ahead and have this issue be closed for now.
