### ISSUE TITLE
About: Update info on what we do/why we exist (and that we meet 4x a year)

### ISSUE THREAD

**Issue by erikfritas** [ivamp-consortium/ivamp-consortium.github.io#5]

**Comment by erikfritas** [comment]
Ok... Let me get this straight... Is it for me to edit the "About", in the style or in the text itself?

**Comment by sabahzero** [comment]
@erikfritas just to have the font be matching across all pages. at the moment, there are two different fonts. does this answer your question? let me know if i need to be more detailed

**Comment by erikfritas** [comment]
@sabahzero ok, what font do you want me to put? I've been thinking about Open Sans and Montserrat...

**Comment by sabahzero** [comment]
Let's keep the font that takes up most of the site (I think it's Helvetica?) thanks for asking!

**Comment by erikfritas** [comment]
Ok, I thank you for answering
